#!/usr/bin/env bash

pushd dotfile
FILES=*
for file in $FILES; do
  cp $file "../.$file"
done;
popd

echo '[ -f "~/.exports"] && . ~/exports' >> ~/.profile
echo '[ -f "~/.alias"] && . ~/alias' >> ~/.profile